namespace SFGServer.Services;

public class TokenSigner
{
    public const string UserIdClaimKey = "UserId";
    public const string GuestUsernameClaimKey = "GuestUsername";

    public string JwtSigningKey { get; }

    public TokenSigner(IConfiguration configuration)
    {
        // TODO(review): what's the proper way to inject configuration to a class?
        // TODO(warnings): tl;dr: 'GetValue' has 'RequiresUnreferencedCodeAttribute' which can break functionality when trimming application code.
        JwtSigningKey = configuration.GetRequiredSection("Secrets").GetValue<string>("JwtSigningKey");
    }

    // TODO(api-parity): we should customize token generation to maintain compat with tokens generated by JS apis

    public string Sign(Guid userId)
    {
        return JWTBearer.CreateToken(
            signingKey: JwtSigningKey,
            expireAt: DateTime.UtcNow.AddHours(4),
            claims: new [] { (UserIdClaimKey, userId.ToString()) }
        );
    }

    public string SignGuest(string username)
    {
        return JWTBearer.CreateToken(
            signingKey: JwtSigningKey,
            expireAt: null, // no reason for token to expire
            claims: new [] { (GuestUsernameClaimKey, username) }
        );
    }
}
