# https://github.com/microsoft/vscode-dev-containers/blob/master/container-templates/docker-compose/.devcontainer/docker-compose.yml
version: "3"

services:
  devcontainer:
    # Using a Dockerfile is optional, but included for completeness.
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14-buster

    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    # Runs app on the same network as the service container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres

    user: node

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: sfg
      POSTGRES_PASSWORD: dev
